# Generated by Django 6.0.3 on 2026-03-23 03:34

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_seed_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('student_name'), models.F('trip'), name='unique_student_trip_ci'),
        ),
    ]
